# message_connect

```
root@lite3:/home/user/ros2_ws/src/quadruped_bringup/launch# ros2 launch navigation.launch.py 
[INFO] [launch]: All log files can be found below /root/.ros/log/2025-09-17-08-41-13-582615-lite3-92740
[INFO] [launch]: Default logging verbosity is set to INFO
[ERROR] [launch]: Caught exception in launch (see debug for traceback): Caught multiple exceptions when trying to load file of format [py]:
 - PackageNotFoundError: "package 'quadruped_bringup' not found, searching: ['/home/user/ros2_ws/install/nav2_common', '/home/user/ros2_ws/install/autoware_signal_processing', '/home/user/ros2_ws/install/autoware_component_interface_specs', '/opt/ros/humble']"
 - InvalidFrontendLaunchFileError: The launch file may have a syntax error, or its format is unknown


```

